language: perl
perl:
  - "5.10"
before_install:
  - cpanm Error
  - cpanm Net::DNS
  - cpanm NetAddr::IP
  - curl -O http://www.cpan.org/authors/id/J/JM/JMEHNLE/mail-spf/Mail-SPF-v2.9.0.tar.gz
  - tar xzvf Mail-SPF-v2.9.0.tar.gz
  - pushd Mail-SPF-v2.9.0
  - perl Build.PL && ./Build install --install_path sbin=/home/travis/perl5/perlbrew/perls/5.10/sbin
  - popd && rm -rf Mail-SPF-v2.9.0
install:
  - cpanm -v --installdeps --notest .
notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
        - andrew@topdog.za.net
